server:
  port: 12000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.68.3:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-coupon

mybatis-plus:
  # mapper-locations: classpath*全包依赖扫描; classpath自己的mapper
  mapper-locations: classpath:/mapper/**/*.xml
  #  统一设定自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
