server:
  port: 15000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  host: 192.168.56.101:6379
  password: 123456

  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
#  mvc:
#    static-path-pattern: /static/**
mybatis-plus:
  # mapper-locations: classpath*全包依赖扫描; classpath自己的mapper
  mapper-locations: classpath:/mapper/**/*.xml
  #  统一设定自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

logging:
  level:
    com.vector.mallproduct: error
