server:
  port: 19000
spring:
  application:
    name: mall-search
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
es:
  host: 192.168.56.101
  port: 9200

