spring:
  application:
    name: mall-third-party
  cloud:
    alicloud:
      access-key: LTAI5tMXez86xSxjocDM7Y7S
      secret-key: fEME7Db5oG6IDN74eXC9vQsgo8HFe3
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: supermall-project-oss
server:
  port: 18000