spring:
  application:
    name: mall-third-party
  cloud:
    alicloud:
      access-key: xxxxxxxxxxxxxxxxxxx
      secret-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      oss:
        endpoint: oss-cn-xxxxxx.aliyuncs.com
        bucket: xxxxxxx
server:
  port: 18000