spring:
  application:
    name: mall-third-party
  cloud:
    alicloud:
      access-key: xxxxxxxxxxxxxxx
      secret-key: xxxxxxxxxxxxxxxxxxx
      oss:
        endpoint: oss-cn-xxxxxxxxx.aliyuncs.com
        bucket: xxxxxxxxxxxxxxxxx
server:
  port: 18000